# $ docker swarm init
# $ docker stack deploy -c docker-compose.yml g-suite
# version 3 is required for docker swarm
# docker compose
version: '3'
    asdfasd
services:
  
  reverse-proxy:
    build: ./ReverseProxy
    ports:
      - 8080:80
    depends_on:
      - api
      - web
    deploy:
      replicas: 1
  
  api:
    build: ./Api
    volumes:
      - ./Api:/usr/src/app
    deploy:
      replicas: 1
  
  web:
    build: ./Web
    volumes:
      - ./Web:/var/www/html
    depends_on:
      - api
    deploy:
      replicas: 2